### ISSUE TITLE
NU1701 when including in a netstandard2.0 library

### ISSUE THREAD

**Issue by Tragetaschen** [DotNetCross/NativeInts#1]
I'm successfully using this library to reduce the burden that are `size_t` based P/Invokes. Yay!

However, since I added it to my `netstardard2.0` library, restoring gives a warning:
`Warning	NU1701	Package 'System.Runtime 4.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.`

**Comment by nietras** [comment]
@Tragetaschen thanks for reporting this. I will have to check the nuspec file and see what might be wrong.

**Comment by nietras** [comment]
Weird according to http://nugettoolsdev.azurewebsites.net/3.5.0-beta2-1484/get-nearest-framework?project=netstandard2.0&package=netstandard1.0%0D%0ANETFramework4.6 it should select the `netstandard1.0` target framework specified in the nuspec and it seems to do but the `System.Runtime` package is not resolved appropriately.

Added `.NETStandard2.0` target framework to the nuspec and removed the `System.Runtime` dependency for that. Tests show it works, so try out `1.0.0`.

Fixed in https://github.com/DotNetCross/NativeInts/commit/e0b771384096d6dfbd3e0cbd37d0117785e502be

**Comment by Tragetaschen** [comment]
Yup, warning is gone. Thanks! (`0.1.0`, though)

**Comment by nietras** [comment]
@Tragetaschen thanks for letting me now, and yes `0.1.0` my bad 😄
